### ISSUE TITLE
Use surface dial on Recalbox

### ISSUE THREAD

**Issue by byrialsen** [daniel5151/surface-dial-linux#12]
A quick question:

Any idea weather this software/driver can be used to make surface dial work with https://www.recalbox.com/

**Comment by daniel5151** [comment]
I'm not too familiar with this software myself, but from a brief look at its FAQ, it seems that this is simply something you install on an existing PC, such as a raspi / modern PC?

If so, there shouldn't be anything stopping you from running the surface dial driver in the background, and then re-mapping the synthetic keyboard / mouse events it generates to inputs in whatever software you're trying to use it with.
